name: Node Secrets Example

on: push

jobs:
  run-node:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Run Node with secret
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: node app.js
